{
    "tpls":[],
    "filelist":[
		"/js/react/react.min.js",
		"/js/react/react-dom.min.js",
	    	"/js/react/ReactRouter/2.4.0/ReactRouter.min.js",
			"/jsx/home.jsx",
			"/jsx/docviewer/router.jsx"
      ]
}
