{
    "tpls":[],
    "filelist":[
		"/js/react/react.min.js",
		"/js/react/react-dom.min.js",
		"/js/react/ReactRouter/2.4.0/ReactRouter.min.js",
		"/js/jquery-2.1.3.min.js",  
		"/js/jquery.json-viewer.js",
		"/js/showdown/showdown.js",
		"/js/x2js/xml2json.min.js",
		"/js/json2.min.js",			
		"/jsx/home.jsx",
		"/jsx/docviewer/router.jsx"
      ]
}
