{
    "tpls":[],
    "filelist":[
        "/js/react/react.min.js",
        "/js/react/react-dom.min.js",
		"/js/jquery-2.1.3.min.js",
        "/jsx/a1.jsx",
		"/jsx/a3.jsx",
	    	"/jsx/a2.jsx",
	    	"/jsx/form.jsx"
      ]
}
